version: "3.8"

services:
  wifite:
    build:
      context: .
      dockerfile:
        Dockerfile-amd64
    container_name: wifite
    restart: "no"
    network_mode: host
    privileged: true
    volumes:
     - "${HOME}:/home/wifite"